@host = http://localhost:3000/api/restaurants/menus
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY5OTg3MjMxOSwiZXhwIjoxNjk5OTE1NTE5fQ.YwbcoCvUWWgfkLmVL8mIm1MkiZxPaV_rZ-krRv5g9Js


### 메뉴 생성
POST {{host}}
Content-Type: application/json
# Authorization: Bearer {{accessToken}}

{
    "name":"마라샹궈",
    "price": 15000,
    "image": "sdfasjhfdfkjlsjkf",
    "content": "“둘이먹으면 둘다 죽음"
}


### 메뉴 목록 조회 -
GET {{host}}



### 메뉴 수정 --개발완료
PUT {{host}}/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name":"마라샹궈",
    "price": 25000,
    "image": "sdfasjhfdfkjlsjkf",
    "content": "“둘이먹으면 사장님이 죽음"
}

### 메뉴 삭제 -- 개발완료
DELETE {{host}}/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}